### ISSUE TITLE
Detecthomescreen parameter

### ISSUE THREAD

**Issue by basyr** [cubiq/add-to-homescreen#158]
Hi,

Many thanks for the link ! I've downloaded it and trying to get it work.
I was able to get the message so the user needs to add it to his home screen and it worked.  But only on Android and Iphone 6, on Iphone 5, it didn't popup.
But I'm also having trouble with the 'detecthomescreen' parameter.  When I set this to true and I delete my shortcut in the home-screen, the message to add it again to the home screen doesn't popup when I surf in Google chrome to the mobile web app.  The only thing I can do is completely delete the history of google chrome.  What am I doing wrong here ?

Kind regards
Bart

**Comment by rosco1502** [comment]
ATH will only appear once unless you add `addToHomescreen.removeSession()`. This will make it delete the data stored locally on the client device so that it will reopen every time you visit the page/site.
To use this put `<script> addToHomescreen.removeSession() </script>` right after the ath.js is intalized.
Hope this helps!

**Comment by rosco1502** [comment]
Also instead of using the detecthomescreen I used this PHP code 
`$ua = strtolower($_SERVER['HTTP_USER_AGENT']);
if ( strpos($ua,"iphone") || strpos($ua,"ipad") ) {
   if ( strpos($ua,"safari") ) {
     // When in Safari run code below
     
   } else if ( substr_count($ua, '/') === 3 ) {
     // When on homescreen run code below
     // Example: header('Location: HTTP://EXAMPLE.COM/INDEX.HTML');
   }
}` This however **only** works with iOS devices.

**Comment by basyr** [comment]
Hi,
Thanks for you reply. The removeSession() isn't what I'm looking for. 
I just want ATH to popup when the url is not on the users startscreen. But it seems that this isn't possible... So if the user deletes the shortcut,he isn't prompted anymore.

**Comment by cubiq** [comment]
> So if the user deletes the shortcut,he isn't prompted anymore.

this is a technology limit. there's nothing we can do about it.

**Comment by rosco1502** [comment]
The `removeSession()` should make it appear everytime the user visits the
page. But you should ask the developer.
